config/routes.rb
Rails.application.routes.draw do
  resources :user_profile, path: "user/profile"

  root 'welcome#index'
  
  devise_for :admins
  devise_for :users, skip: [:registrations]

 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one :admin_user

  has_one :user_info
  accepts_nested_attributes_for :user_info, reject_if: :all_blank
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

   private
    def after_sign_in_path_for(resource)
      user_profile_path(current_user.id)
    end
end

app/controllers/user_profile_controller.rb
class UserProfileController < ApplicationController
  before_action :authenticate_user!
  layout 'user_layout'

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @is_admin = @user.admin_user.is_admin
  end

  def params_user
    params.require(:user).permit( :email, :password, :password_confirmation, user_info_attributes: [:id, :first_name, :last_name, :address, :gender, :birthdate, :cep, :state])
 end 

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

   def full_title(page_title = '')
      base_title = 'BTT'
      if page_title.empty?
         base_title
      else 
         "#{page_title} | #{base_title}"
      end
   end

   
end

app/helpers/user_profile_helper.rb
module UserProfileHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= params %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/user_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Layout User</h1>
    <p><%= params %></p>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_login_logout.html.erb
<% if user_signed_in? %>
   Logado como: <strong><%= current_user.email %></strong><br>
   <%#= link_to 'Editar perfil', edit_admin_registration_path, :class => 'navbar-link' %> 
   <%= link_to "Logout", destroy_admin_session_path, method: :delete %>
<% else %>
   <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/user_profile/index.html.erb
<% provide(:title, "Profile") %>

<h1>UserProfile#index</h1>
<p>Find me in app/views/user_profile/index.html.erb</p>

<%= link_to 'Welcome', root_path %>

<hr>
<% @users.each do |user| %>
   <p>Email: <%= user.email %> | Admin: <%= user.admin_user.is_admin %></p>
<% end %>

app/views/user_profile/show.html.erb
<h1>Show</h1>
<p><%= @user.email %></p>
<p>Tem privilégios administrativos: <%= @is_admin %></p>
<p><%= link_to "Logout", destroy_admin_session_path, method: :delete %></p>

<% if @is_admin %>
   <p><%= link_to "Listar todos os usuários", user_profile_index_path %></p>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<% provide(:title, "Home") %>

<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% unless user_signed_in? %>
   <%= link_to "Login", new_user_session_path %>
<% else %>
   <%= link_to "Profile", user_profile_index_path %>
<% end %>